### ISSUE TITLE
Оформление меню

### ISSUE THREAD

**Issue by i-ka** [i-ka/The_Overhead#9]
Нужно найти/нарисовать картинку для заднего фона меню и текстуры для кнопок
- [x] Главное меню
- [x] Меню паузы
- [x] Экран смерти игрока

**Comment by VChet** [comment]
- 065c4d49039608dc0d44a42047c20f46d6c24c77 и b2912961cdb3f7cc05da361cc80dd8a22814b73d
- dc1d5ab99522d2622fc984bad1f190f581b60de0
- 5c962dc25bcc505efb00b31323ab7b374654fac5
